### ISSUE TITLE
Automatically add generated files to fsproj

### ISSUE THREAD

**Issue by simon-reynolds** [efcore/EFCore.FSharp#20]
Both scaffolding and creating migrations results in new files being added to the project

Unlike C# the compilation order of F# is important so we will need to add them to the fsproj in the appropriate place within the project

Currently any generated files have to be added to the fsproj file manually

**Comment by RonaldDijks** [comment]
This might be something we cannot get around without considerable work. If we were to also generate the includes, we'd have to either:

1. Make assumptions about the project structure and order of imports.
2. Actually figure out the order of imports, which probably would be doable buy waaaay outside of the projects scope at the moment.

I think that if we mention it in the docs, it would be fine, because once you know where the migrations are created you can just add `migrations/*` (I assume).

As much as I love ordered imports, this is one of the problems that I ran into a few times while generating F# code for other projects.

Is this a must have, or can we do without it? :)

**Comment by bricelam** [comment]
Can we just update [Bricelam.EntityFrameworkCore.FSharp.targets](https://github.com/bricelam/EFCore.FSharp/blob/master/EFCore.FSharp/build/netstandard2.0/Bricelam.EntityFrameworkCore.FSharp.targets) with this:?

``` xml
<ItemGroup>
  <CompileAfter Include="$(MSBuildProjectDirectory)Migrations\**\*.fs" />
</ItemGroup>
```

**Comment by bricelam** [comment]
Well, probalby with some hooks for those who deviate from the defaults...

``` xml
<PropertyGroup>
  <EFCoreMigrationsDir Condition="'$(EFCoreMigrationsDir )' == ''">$(MSBuildProjectDirectory)Migrations\</EFCoreMigrationsDir>
</PropertyGroup>
<ItemGroup>
  <CompileAfter Include="$(EFCoreMigrationsDir )**\*.fs" />
</ItemGroup>
```

**Comment by bricelam** [comment]
We may even be able to warn when they deviate. Something like...

> 📎 It looks like you're trying to scaffold migrations into a custom directory. Did you know can set the EFCoreMigrationsDir MSBuild property to have these files included automatically?

**Comment by simon-reynolds** [comment]
Closing as duplicate of #43
