### ISSUE TITLE
Generated migration file does not compile

### ISSUE THREAD

**Issue by isaacabraham** [efcore/EFCore.FSharp#44]
A newly-created migration has an `open` statement at the top of the file but no namespace or module. This isn't valid F# and must be deleted before it compiles.

**Comment by drk-mtr** [comment]
I think I'm only seeing this on Windows but I haven't tested much.

**Comment by DurdSoft** [comment]
This happens when the `DbContext` is not in a namespace. 

`contextType.Namespace` here: https://github.com/efcore/EFCore.FSharp/blob/12457eb3cf522db122ba134ddda2570a7f7595d2/src/EFCore.FSharp/Migrations/Design/FSharpMigrationsGenerator.fs#L264 is null in that case and gets appended as such to the sequence. 

Fix is as simple as adding `|> Seq.filter (isNull >> not)` to the end of the line - I've opened a PR: https://github.com/efcore/EFCore.FSharp/pull/50
